In [ ]:
!pip install -q torchmetrics[audio]
!pip install -q librosa requests soundfile pandas tqdm

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 73.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 51.0 MB/s eta 0:00:00
  Building wheel for pesq (setup.py) ... done

In [ ]:
!git clone https://github.com/gabrielmittag/NISQA.git
%cd NISQA

!pip install -q torch torchaudio

Cloning into 'NISQA'...
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 258 (delta 55), reused 45 (delta 45), pack-reused 188 (from 1)
Receiving objects: 100% (258/258), 2.27 MiB | 18.05 MiB/s, done.
Resolving deltas: 100% (130/130), done.
/content/NISQA

In [ ]:
import torch
import librosa
import pandas as pd
import numpy as np

from tqdm import tqdm

from torchmetrics.audio import NonIntrusiveSpeechQualityAssessment

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

nisqa = NonIntrusiveSpeechQualityAssessment(
    fs=16000
).to(device)

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/tts_benchmark/vits_coqui/wavs/tts_dataset.csv"
)

df.head()

,audio_path,text,tts_runtime,audio_duration,tts_rtf
0,/content/drive/MyDrive/tts_benchmark/vits_coqu...,جسد مزبور را در بیشهای که در گودی کوهستان قرار...,0.286352,5.750000,0.049800
1,/content/drive/MyDrive/tts_benchmark/vits_coqu...,لیدی گاگای تازه وارد به یکباره,0.203337,3.616667,0.056222
2,/content/drive/MyDrive/tts_benchmark/vits_coqu...,رازی را آشکار کردن,0.176803,2.923333,0.060480
3,/content/drive/MyDrive/tts_benchmark/vits_coqu...,ماه هاست سکوت کردم,0.213462,3.168667,0.067366
4,/content/drive/MyDrive/tts_benchmark/vits_coqu...,چه کسی این نامه را فرستاده است,0.171248,3.510000,0.048789

In [ ]:
import pandas as pd

df[["audio_path"]].rename(
    columns={"audio_path": "deg"}
).to_csv(
    "nisqa_input.csv",
    index=False
)

In [ ]:
!python /content/NISQA/run_predict.py \
    --mode predict_dir \
    --pretrained_model /content/NISQA/weights/nisqa.tar \
    --data_dir /content/drive/MyDrive/tts_benchmark/vits_coqui/wavs

Device: cuda
Model architecture: NISQA_DIM
Loaded pretrained model from /content/NISQA/weights/nisqa.tar
# files: 1052
---> Predicting ...
/usr/local/lib/python3.12/dist-packages/librosa/feature/spectral.py:2148: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)
/usr/local/lib/python3.12/dist-packages/librosa/feature/spectral.py:2148: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)
      deg  mos_pred  noi_pred  dis_pred  col_pred  loud_pred
00053.wav  3.375427  3.576253  3.920771  3.834170   4.042232
00054.wav  3.079578  3.288981  4.144946  3.750424   4.095434
00058.wav  2.934200  4.273874  3.039011  3.483601   3.771841
00055.wav  3.987279  4.159868  4.340854  4.163558   4.174575
00056.wav  3.298699  3.306867  4.407313  3.886342   4.518110
00057.wav  2.622261  3.118353  3.827072  3.567677   3.631376
00059.wav  2.711150  3.212286  3.787353  3.455519   3.776412
00061.wav  3.618907  3.986941  4.519128  2.957470   4.094970
00060.wav  2.097353  2.420436  3.320995  3.537508   3.782998
00062.wav  2.003820  2.916069  3.081635  3.206546   2.483896
00063.wav  3.449918  3.674860  4.299280  3.516980   4.395470
00064.wav  2.764886  3.361600  3.607376  3.659223   3.573733
00065.wav  3.188314  3.815941  4.024618  3.779258   3.889684
00066.wav  2.686921  3.050289  4.143044  3.955379   4.340436
00067.wav  4.176262  3.883142  4.616831  4.423723   4.526847
00068.wav  3.446944  3.803817  4.301116  3.658128   4.332024
00070.wav  4.577658  4.210021  4.766457  4.178601   4.537098
00069.wav  3.305531  3.712396  4.003012  3.745092   3.942602
00071.wav  3.891937  4.261973  4.229945  4.151170   4.236496
00073.wav  2.674288  3.458651  3.864976  3.133875   3.721801
00072.wav  2.966659  3.199091  3.867728  3.727361   3.908729
00074.wav  2.850717  3.408454  3.761407  3.607735   3.724607
00075.wav  4.439535  4.288417  4.606813  4.233080   4.490506
00076.wav  2.919382  3.487070  4.146297  3.867423   4.078322
00077.wav  3.856125  4.015051  4.226451  3.812782   4.193847
00078.wav  3.372125  3.522088  4.315957  3.879011   4.312341
00079.wav  4.541735  4.283605  4.649204  4.417744   4.610449
00080.wav  3.259349  3.441189  4.058645  3.784152   3.952486
00082.wav  3.918762  3.760699  4.377305  3.990561   4.319554
00081.wav  2.944741  3.268121  3.977349  3.619085   4.089873
00083.wav  4.774049  4.312850  4.769555  4.383310   4.660292
00084.wav  2.341789  2.812656  3.830647  3.158367   3.860421
00085.wav  3.974613  4.143013  4.287584  3.960618   4.203578
00086.wav  3.078015  3.043259  3.667434  3.842036   3.844922
00087.wav  2.961895  3.214182  4.060217  3.770990   4.199385
00088.wav  3.975812  4.048338  3.910722  3.823837   4.009983
00089.wav  3.673971  3.824679  3.942520  3.653521   3.997091
00090.wav  3.343599  3.553597  4.244177  3.869272   4.237848
00091.wav  3.119655  3.436929  3.597112  3.516223   3.647746
00092.wav  3.223686  3.699346  3.892943  3.717609   3.821296
00093.wav  2.794386  3.533578  3.794512  3.629998   3.482168
00095.wav  2.355362  2.974422  3.715094  3.460124   3.849685
00094.wav  4.648650  4.565667  4.442669  4.431471   4.387922
00096.wav  2.974775  3.327164  3.706342  3.440206   3.539567
00097.wav  3.140451  2.859065  3.933527  3.937932   3.772516
00098.wav  3.563461  3.836277  4.220712  3.991049   4.109170
00100.wav  3.026612  3.323634  4.027827  3.799517   4.109631
00099.wav  3.479794  3.863597  3.836461  3.780930   3.765823
00101.wav  2.651467  3.238310  3.679958  3.470999   3.827946
00102.wav  4.057392  4.410290  3.988297  4.186189   4.139873
00103.wav  2.815233  3.462647  3.967222  3.305814   3.991317
00104.wav  2.558794  2.956397  3.831983  3.872102   4.083541
00105.wav  4.071508  3.924134  3.991031  4.047012   4.157360
00106.wav  2.932049  3.233633  3.668924  3.506066   3.687249
00109.wav  3.118453  3.453341  3.911629  3.715099   3.916004
00107.wav  3.577843  3.464669  4.009539  3.850398   4.024521
00108.wav  3.892520  4.559635  4.264677  4.219758   4.096131
00110.wav  3.006542  3.385150  3.276605  3.782438   3.519256
00112.wav  2.729314  2.991350  4.034433  3.621524   4.004978
00113.wav  2.631701  3.321787  3.668701  3.337332   3.942647
00111.wav  3.727999  4.232705  4.071862  3.836676   3.982610
00115.wav  3.892771  3.765778  4.502950  3.788959   4.443916
00114.wav  3.551346  3.590839  4.460835  3.986821   4.471556
00116.wav  4.348822  4.297731  4.395864  4.296329   4.249702
00117.wav  2.634120  3.102398  3.725041  3.628664   3.633680
00118.wav  3.758045  3.685919  4.173676  4.072524   4.250870
00120.wav  3.312744  3.531529  4.305886  3.575949   4.133445
00119.wav  4.470109  4.200439  4.477918  4.266862   4.406871
00121.wav  4.366003  4.453673  4.245591  4.335227   4.190102
00122.wav  3.836937  3.448925  3.617707  3.838528   3.678467
00123.wav  4.431096  4.244627  4.538430  4.168380   4.515831
00125.wav  2.612442  3.024045  3.237935  3.494500   3.340335
00124.wav  3.832032  4.036653  3.815331  3.965625   4.178889
00126.wav  2.523467  3.016121  3.997722  3.547973   4.284127
00127.wav  2.551130  3.422270  3.490308  3.964430   3.780483
00128.wav  2.768474  3.272789  3.673579  3.683646   3.929519
00129.wav  3.232875  3.765995  4.130723  4.085355   4.393053
00130.wav  3.826425  3.951286  4.559487  3.805199   4.556040
00131.wav  3.984756  3.914243  4.152496  4.013631   4.206979
00132.wav  2.672114  3.121452  3.558025  3.650073   3.831124
00133.wav  2.896347  3.458094  3.983504  3.783446   4.071377
00134.wav  4.773871  4.638052  4.694673  4.549640   4.587440
00135.wav  3.717677  3.641055  4.376646  4.054905   4.476940
00137.wav  3.192285  3.481698  3.813396  3.351113   3.665376
00136.wav  3.164151  3.159725  4.477473  3.825460   4.366484
00139.wav  2.997195  3.586062  3.858103  3.568187   3.798254
00138.wav  3.519843  3.509150  4.053105  3.947298   3.931319
00140.wav  2.799056  3.193744  3.674752  3.619225   3.784863
00141.wav  2.964420  3.342731  4.233351  3.698342   4.095730
00142.wav  2.340357  2.849324  3.858964  3.547991   3.500237
00143.wav  2.516260  3.101978  3.829772  3.486346   3.716933
00145.wav  4.087861  4.278799  4.394901  4.139997   4.260047
00144.wav  2.865137  3.066727  3.837661  3.626278   3.982167
00146.wav  2.968632  3.763501  4.069564  3.834086   4.117612
00147.wav  4.283676  4.090002  4.372498  4.201766   4.280807
00148.wav  3.841361  3.854195  4.181404  3.948037   4.223686
00149.wav  4.249974  4.501256  4.446197  4.290101   4.310523
00150.wav  3.991320  4.074853  4.189864  3.937536   4.255745
00151.wav  3.534672  3.826566  4.182971  3.775381   4.211721
00153.wav  3.711684  4.085485  4.399541  4.052259   4.250684
00152.wav  3.182306  3.707021  3.908073  3.759801   4.074971
00154.wav  4.004049  4.144179  4.576599  4.003299   4.496555
00155.wav  2.604990  3.370717  3.744559  3.228519   3.779374
00158.wav  2.493142  3.154579  3.438469  3.316351   3.305003
00156.wav  3.525702  3.777373  3.916182  3.786071   4.103180
00159.wav  3.250655  3.443901  4.175387  3.852918   4.245422
00157.wav  4.205132  4.371245  4.546116  4.427798   4.423279
00160.wav  3.449222  3.842382  4.376901  3.090187   4.289657
00161.wav  3.337898  3.396022  3.905375  3.777001   3.893878
00162.wav  4.031355  3.899478  4.127613  4.032889   4.267564
00163.wav  1.999581  2.761165  2.996533  3.178702   3.778312
00164.wav  3.881847  3.545916  4.329761  3.853151   4.138907
00165.wav  4.427629  4.421972  4.270113  4.290240   4.299866
00166.wav  2.903370  3.290349  3.975048  3.840864   3.910124
00168.wav  2.986448  3.414496  3.932432  3.543413   3.982225
00167.wav  4.234724  3.898529  4.037990  4.163548   3.962193
00169.wav  3.412132  3.925534  4.194365  3.821515   4.144560
00171.wav  3.474111  3.840876  4.111537  3.719814   4.202842
00170.wav  4.211897  4.153991  4.289212  4.156539   4.277124
00172.wav  3.279843  2.683863  3.694061  3.704471   3.846167
00173.wav  4.114019  4.159635  4.367372  4.125351   4.282757
00174.wav  4.011362  4.026605  4.243050  4.161288   4.218108
00175.wav  3.581481  3.466453  3.553640  3.826018   3.906831
00176.wav  2.943451  3.506855  3.949903  3.634045   3.908602
00178.wav  3.630791  3.931305  4.248658  3.550192   4.345591
00177.wav  3.149701  3.433230  3.869015  3.719047   3.900660
00179.wav  3.315304  3.630114  4.140509  3.524844   4.274527
00180.wav  3.003414  3.156708  3.970694  3.914214   4.106554
00181.wav  3.438128  3.407140  3.944694  3.759335   4.134319
00183.wav  2.745543  3.323416  4.080768  3.492465   3.874485
00182.wav  2.943257  3.343406  4.250929  3.846239   4.264654
00185.wav  4.111223  4.300237  4.111960  3.925850   4.130552
00184.wav  2.686680  3.205974  3.678777  3.624521   3.662000
00186.wav  2.414945  3.302371  3.529229  3.474435   3.052884
00187.wav  3.029767  3.309895  3.900939  3.836513   3.993745
00190.wav  3.816725  3.795220  4.303786  3.837259   4.331787
00189.wav  2.444063  3.094655  3.823842  3.210706   3.720362
00188.wav  3.432653  3.438864  4.577516  3.807351   4.435991
00192.wav  3.565405  4.172632  4.246721  3.724379   3.979119
00191.wav  3.758352  3.700488  4.064782  3.769845   4.103287
00193.wav  3.119038  3.309906  4.101864  3.912069   4.308084
00194.wav  3.021609  3.670172  4.165356  3.578474   4.108257
00196.wav  3.301412  3.911549  3.993467  3.793388   3.966642
00195.wav  2.824405  3.513103  3.910483  3.332415   3.659181
00198.wav  3.291493  3.731778  4.094013  3.719328   4.194646
00197.wav  3.641215  3.671787  3.959661  4.056391   4.052198
00200.wav  3.478094  3.680636  3.999251  3.823854   4.002538
00199.wav  3.031858  3.959854  4.162047  4.085789   4.364899
00202.wav  2.764511  3.538853  3.824670  3.507724   3.658883
00201.wav  3.673233  3.921222  3.978817  3.773009   4.091490
00203.wav  3.555654  3.767034  4.008800  4.074177   4.253760
00204.wav  3.647433  3.840244  4.349683  4.145845   4.393671
00205.wav  2.838255  3.262430  4.236348  3.902790   4.293202
00206.wav  4.187717  4.018448  4.482170  3.577057   4.354661
00208.wav  4.325495  4.020925  4.534741  4.294355   4.476595
00207.wav  2.116998  2.907362  3.410755  3.713722   3.882144
00209.wav  2.757599  3.043695  4.199636  3.876705   4.107061
00210.wav  3.549254  3.538422  4.354137  3.973962   4.346589
00212.wav  2.917115  3.719037  4.178718  3.815343   4.171709
00211.wav  3.585593  3.846614  4.080466  3.850904   4.062850
00213.wav  3.026369  3.381315  4.190624  3.858402   4.211812
00214.wav  3.457588  3.868696  4.410684  3.590489   4.251320
00215.wav  3.078529  3.335060  4.001552  3.732358   4.115755
00216.wav  3.960008  3.783663  4.356645  3.997821   4.309095
00217.wav  2.381468  2.825429  3.540053  3.587003   3.581211
00218.wav  4.131023  4.113397  4.317424  4.163582   4.318564
00219.wav  3.952091  4.082871  4.307539  3.881934   4.234815
00221.wav  2.472298  2.967908  3.694129  3.564036   3.784078
00220.wav  3.365739  3.504769  4.136203  3.466077   4.137069
00222.wav  4.180564  4.165453  4.278453  4.197426   4.194553
00223.wav  4.615217  4.547403  4.714858  4.517378   4.621929
00224.wav  3.330920  3.681567  3.937341  3.906504   3.918393
00225.wav  3.131285  3.398468  3.925213  3.710384   4.037931
00226.wav  3.251882  3.505476  4.185520  3.914276   4.281277
00227.wav  3.999499  4.132462  4.121734  3.935783   4.186100
00229.wav  3.615786  3.860776  4.168180  3.972401   4.051171
00230.wav  2.637372  3.088929  3.775039  3.517975   3.840448
00228.wav  4.050484  4.134239  4.220325  4.281669   3.996577
00231.wav  2.313177  2.902468  3.469494  3.258382   3.203728
00232.wav  3.303188  3.799555  4.119508  3.650668   4.025644
00233.wav  2.551639  3.308155  3.605639  3.372687   3.579723
00235.wav  4.232090  3.612811  4.262043  3.872738   4.306584
00234.wav  2.925821  3.418944  3.929223  3.823834   3.949656
00236.wav  4.031611  4.064480  4.275462  3.888941   4.153481
00237.wav  2.965226  3.703741  3.894482  4.166710   4.171717
00238.wav  3.601944  4.132980  3.802872  3.616631   4.060693
00239.wav  3.411457  3.889302  4.373400  3.834219   4.425400
00240.wav  3.705499  3.905643  4.293696  3.859259   4.329833
00241.wav  2.599032  3.109964  3.758060  3.428228   3.511628
00243.wav  4.268233  4.261024  4.219512  4.081005   4.273002
00242.wav  2.791111  3.307951  4.206947  3.745651   4.284564
00244.wav  4.758379  4.549617  4.563617  4.415769   4.549798
00245.wav  3.109746  3.669309  3.809088  3.703366   3.936661
00246.wav  3.338268  3.927319  3.951447  3.757977   3.878639
00247.wav  3.095127  3.628672  4.185005  3.296896   4.026689
00248.wav  3.764140  3.740995  4.232852  4.035263   4.184669
00249.wav  4.376488  4.191808  4.424824  4.256337   4.288943
00250.wav  3.138203  3.673658  3.782701  3.660576   3.638947
00251.wav  2.954703  3.332123  3.948310  3.685170   3.998125
00252.wav  3.611540  3.831241  3.973428  3.596875   3.938847
00253.wav  4.130437  4.101351  4.307879  4.138783   4.265660
00255.wav  3.309974  3.373858  3.706614  3.659573   3.802748
00254.wav  2.827833  3.369009  4.066729  3.249840   3.881766
00257.wav  2.787013  3.359618  4.269258  3.270116   4.231131
00256.wav  3.727519  4.075675  4.268381  4.027558   4.216961
00260.wav  4.207799  3.880131  4.558272  4.303811   4.391199
00258.wav  3.268995  3.650780  4.159233  4.152528   4.193457
00259.wav  3.321021  4.108579  3.931280  3.727019   3.785025
00261.wav  3.278185  3.780805  4.013231  3.724377   4.049014
00262.wav  4.585643  4.478965  4.596066  4.425091   4.505623
00263.wav  3.257158  3.424587  4.101587  3.715129   4.204861
00264.wav  2.736410  3.003702  4.101051  3.873956   4.101368
00265.wav  2.354140  2.974999  3.488353  3.415464   3.458401
00266.wav  2.661743  2.985677  3.642768  3.628495   3.751181
00267.wav  2.731725  3.396712  3.701601  3.399066   3.659655
00268.wav  3.836369  4.222672  3.023037  3.878677   4.079980
00269.wav  3.994077  3.853494  4.409506  3.970412   4.327558
00270.wav  2.876638  3.364428  4.109727  3.970965   4.326188
00271.wav  3.758191  3.882259  4.145061  3.996122   4.068989
00272.wav  2.435778  3.555241  2.915918  3.359455   3.447107
00273.wav  4.339670  4.060891  4.430089  4.090029   4.320400
00274.wav  3.359192  3.278992  3.998624  3.840863   4.005849
00275.wav  4.379209  4.442616  4.309017  4.386943   4.313595
00276.wav  3.529812  4.070318  4.465881  3.089138   4.314312
00279.wav  3.716706  4.151612  3.965759  3.971210   4.049296
00277.wav  3.355059  3.676564  4.060289  4.168734   4.064771
00278.wav  3.002465  3.241440  3.772827  3.649877   3.770634
00280.wav  3.073980  3.408738  3.926400  3.733359   3.962067
00281.wav  3.924470  4.256745  4.090239  4.110742   3.985197
00282.wav  3.817711  4.393103  4.081541  3.965928   4.150169
00283.wav  3.106325  3.747969  3.913082  3.733463   3.994497
00284.wav  3.583472  3.784409  4.115919  3.902529   4.125715
00285.wav  4.513528  4.495883  4.656853  4.522099   4.633282
00286.wav  3.960162  4.009883  4.390217  4.215070   4.436668
00287.wav  3.179619  3.448910  4.116582  3.943904   4.092587
00288.wav  3.268283  3.552984  3.963461  3.613522   4.100415
00290.wav  4.588593  4.322871  4.502335  4.231319   4.293663
00289.wav  4.232761  3.552542  4.447194  4.209208   4.439471
00291.wav  2.965266  3.129789  4.004869  3.730277   4.117376
00292.wav  2.686450  2.791741  3.874843  3.661856   3.941069
00295.wav  2.704685  3.041687  3.692551  3.599812   3.755430
00293.wav  3.537861  3.471045  3.828567  3.773838   3.739589
00294.wav  4.596980  4.370378  4.475201  4.475366   4.320050
00296.wav  4.034107  3.920873  4.435863  3.799695   4.217475
00298.wav  2.576853  3.012462  3.731976  3.562278   4.075614
00297.wav  3.623018  3.816199  4.189494  3.765899   4.129399
00299.wav  4.109399  4.516634  4.341254  4.203929   4.259264
00301.wav  4.341083  4.094394  4.543395  4.267190   4.487218
00302.wav  3.765915  3.349941  4.464944  4.136624   4.475872
00300.wav  3.114202  3.295775  4.023428  3.683268   4.032347
00303.wav  3.443523  3.616107  3.932052  3.725487   4.051383
00306.wav  3.145801  3.545132  3.670251  3.757984   3.660961
00304.wav  3.857668  4.331918  4.345415  3.962667   4.150979
00305.wav  2.996719  3.232314  3.949946  3.501401   3.912328
00307.wav  4.270065  4.395253  4.561803  4.282880   4.370899
00308.wav  2.678012  2.663856  3.924263  3.916162   4.373323
00309.wav  3.904792  3.906757  4.162325  3.790060   4.156779
00310.wav  3.294817  3.505579  4.298207  4.086489   4.427152
00311.wav  4.606330  4.429894  4.548161  4.353827   4.505929
00312.wav  3.298935  3.473542  4.267348  3.977748   4.333976
00313.wav  4.316928  4.322709  4.338887  3.975568   4.227044
00314.wav  3.162079  3.674961  3.892798  3.645844   3.767047
00315.wav  2.949592  3.117579  3.600390  3.666718   3.490730
00317.wav  3.331830  3.478996  3.858589  4.014852   4.342037
00316.wav  3.094437  3.471927  4.004606  3.843021   3.896970
00318.wav  3.965839  3.982991  4.491187  4.285306   4.403862
00319.wav  3.054566  3.395206  4.214725  3.788890   4.065462
00321.wav  2.952340  2.848633  4.262927  3.701832   4.281983
00320.wav  2.656812  3.246291  3.495579  3.464832   3.864453
00322.wav  2.163532  2.510895  4.157986  3.698010   4.181881
00323.wav  2.801972  3.255520  4.045198  3.531169   4.110781
00324.wav  3.338562  3.715270  4.058578  3.641397   4.078377
00325.wav  3.095204  3.474767  3.862776  3.619362   3.807145
00326.wav  3.275086  3.888839  4.194793  3.474684   4.218748
00327.wav  3.521965  3.806625  4.090584  3.943815   4.160687
00328.wav  3.179873  3.538069  4.124942  3.697005   4.113473
00329.wav  4.006559  4.060783  4.289997  3.836195   4.068177
00330.wav  3.246316  3.776680  3.918576  3.582044   3.886598
00331.wav  3.303497  3.258336  4.380818  3.787040   4.211165
00332.wav  2.671058  3.133326  3.674743  3.579222   3.956130
00333.wav  3.546150  3.609673  4.252796  3.931405   4.251956
00336.wav  3.048965  3.335891  3.896761  3.440843   3.944728
00334.wav  2.640727  3.224078  4.041820  3.560363   3.825432
00335.wav  2.216032  3.183325  3.492056  3.365711   3.413460
00337.wav  3.814764  4.537169  3.362888  4.242603   4.536728
00339.wav  3.291764  3.587269  4.105874  3.801179   3.992068
00338.wav  2.991001  3.249233  3.800252  3.532186   3.747333
00340.wav  3.890913  3.201042  4.495287  4.028803   4.462168
00341.wav  3.640987  3.864980  4.246585  3.895864   4.116325
00343.wav  2.928506  3.242499  3.969065  3.679654   3.927325
00342.wav  2.202673  2.973937  3.524525  3.172767   3.381677
00344.wav  3.870822  4.094210  4.249152  3.975063   4.176573
00345.wav  2.962834  3.693549  3.807030  3.472699   3.736888
00346.wav  3.232764  3.817172  4.162299  3.806809   4.203216
00347.wav  4.554603  3.248539  4.613135  4.586400   4.427441
00348.wav  2.958251  3.208981  3.592611  3.626434   3.593217
00349.wav  2.950480  3.749437  3.430811  3.610075   3.942502
00350.wav  3.330624  3.380458  4.434965  3.685587   4.259613
00352.wav  3.607860  4.216337  4.169586  3.599328   4.043618
00351.wav  3.063158  3.701574  4.159482  3.584896   4.356889
00353.wav  3.249440  3.338399  3.954296  3.862549   4.077829
00354.wav  3.653881  3.870464  4.350601  3.995240   4.299039
00355.wav  3.881818  3.681019  4.667949  3.651721   4.433818
00356.wav  3.074523  3.636548  3.932450  3.776027   3.963393
00357.wav  3.740841  3.994828  4.505108  4.090928   4.487064
00358.wav  3.876311  3.844606  4.148190  4.228695   4.157022
00360.wav  4.211367  4.060860  4.331973  3.937314   4.300823
00359.wav  4.544903  4.254086  4.574141  4.355566   4.503003
00361.wav  2.825247  3.416005  2.173683  2.948905   3.889487
00362.wav  3.845700  4.291914  3.503869  4.178023   4.200661
00363.wav  3.053940  3.760244  3.950542  3.878511   4.170101
00364.wav  3.855390  3.643958  4.367893  4.207445   4.549430
00365.wav  2.924685  3.598174  4.285628  3.684203   4.008797
00367.wav  4.729815  4.358249  4.516937  4.320656   4.488480

In [ ]:
import os

for root, dirs, files in os.walk("/content/NISQA"):
    for f in files:
        if f.endswith(".csv"):
            print(os.path.join(root, f))

/content/NISQA/nisqa_input.csv

In [ ]:
import pandas as pd

nisqa = pd.read_csv("/content/NISQA/nisqa_input.csv")

print(nisqa.head())

                                                 deg
0  /content/drive/MyDrive/tts_benchmark/vits_coqu...
1  /content/drive/MyDrive/tts_benchmark/vits_coqu...
2  /content/drive/MyDrive/tts_benchmark/vits_coqu...
3  /content/drive/MyDrive/tts_benchmark/vits_coqu...
4  /content/drive/MyDrive/tts_benchmark/vits_coqu...

In [ ]:
import os

for root, dirs, files in os.walk("/content/NISQA"):
    for f in files:
        if f.endswith(".csv"):
            print(os.path.join(root, f))

/content/NISQA/nisqa_input.csv

In [ ]:
!find /content -name "*.csv" | grep -i nisqa

/content/NISQA/nisqa_input.csv

In [ ]:
!find /content -type f | grep -i result

/content/drive/MyDrive/asr_project/w2v_results.csv
/content/drive/MyDrive/asr_project/whisper_large-v3_results.csv
/content/drive/MyDrive/asr_project/wav2vec2_persian_v3_results.csv
/content/drive/MyDrive/asr_project/nemo_fastconformer_results.csv
/content/drive/MyDrive/asr_project/vosk_results.csv
/content/drive/MyDrive/asr_project/vosk_42_results.csv
/content/drive/MyDrive/tts_benchmark/vits_coqui/asr_results.csv

In [ ]:
import sys
sys.path.append("/content/NISQA")

from nisqa.NISQA_model import nisqaModel

In [ ]:
!python /content/NISQA/run_predict.py \
  --mode predict_dir \
  --pretrained_model /content/NISQA/weights/nisqa.tar \
  --data_dir /content/drive/MyDrive/tts_benchmark/vits_coqui/wavs \
  > /content/nisqa_output.txt

/usr/local/lib/python3.12/dist-packages/librosa/feature/spectral.py:2148: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)
/usr/local/lib/python3.12/dist-packages/librosa/feature/spectral.py:2148: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)

In [ ]:
import re
import pandas as pd

rows = []

with open("/content/nisqa_output.txt", "r", encoding="utf-8") as f:
    for line in f:

        line = line.strip()

        # rows look like:
        # 00053.wav  3.375427  3.576253  3.920771  3.834170   4.042232

        if re.match(r"^\d+\.wav", line):

            parts = line.split()

            if len(parts) >= 6:

                rows.append({
                    "file": parts[0],
                    "mos_pred": float(parts[1]),
                    "noi_pred": float(parts[2]),
                    "dis_pred": float(parts[3]),
                    "col_pred": float(parts[4]),
                    "loud_pred": float(parts[5]),
                })

nisqa_df = pd.DataFrame(rows)

print(nisqa_df.head())
print("Samples:", len(nisqa_df))

        file  mos_pred  noi_pred  dis_pred  col_pred  loud_pred
0  00053.wav  3.375427  3.576253  3.920771  3.834170   4.042232
1  00054.wav  3.079578  3.288981  4.144946  3.750424   4.095434
2  00058.wav  2.934200  4.273874  3.039011  3.483601   3.771841
3  00055.wav  3.987279  4.159868  4.340854  4.163558   4.174575
4  00056.wav  3.298699  3.306867  4.407313  3.886342   4.518110
Samples: 1052

In [ ]:
summary = pd.DataFrame([{
    "model": "Kamtera_VITS",
    "samples": len(nisqa_df),
    "nisqa_mos_mean": nisqa_df["mos_pred"].mean(),
    "nisqa_mos_std": nisqa_df["mos_pred"].std(),
    "noise_mean": nisqa_df["noi_pred"].mean(),
    "discontinuity_mean": nisqa_df["dis_pred"].mean(),
    "coloration_mean": nisqa_df["col_pred"].mean(),
    "loudness_mean": nisqa_df["loud_pred"].mean(),
}])

print(summary)

          model  samples  nisqa_mos_mean  nisqa_mos_std  noise_mean  \
0  Kamtera_VITS     1052        3.380342       0.611121    3.631798

   discontinuity_mean  coloration_mean  loudness_mean
0            4.077343         3.814252       4.098155

In [ ]:
SAVE_PATH = "/content/drive/MyDrive/tts_benchmark/kamtera_vits_nisqa_summary.csv"

summary.to_csv(
    SAVE_PATH,
    index=False
)

print("Saved to:")
print(SAVE_PATH)

Saved to:
/content/drive/MyDrive/tts_benchmark/kamtera_vits_nisqa_summary.csv

In [ ]:
args = {
    "mode": "predict_dir",
    "pretrained_model": "/content/NISQA/weights/nisqa.tar",
    "data_dir": "/content/drive/MyDrive/tts_benchmark/vits_coqui/wavs",
}

nisqa = nisqaModel(args)
results = nisqa.predict()

Device: cuda
Model architecture: NISQA_DIM
Loaded pretrained model from /content/NISQA/weights/nisqa.tar
# files: 1052

KeyError: 'ms_channel'

In [ ]:
summary = pd.DataFrame([{
    "model": "Kamtera_VITS",
    "samples": len(nisqa),
    "nisqa_mos_mean": nisqa["mos_pred"].mean(),
    "nisqa_mos_std": nisqa["mos_pred"].std(),
    "nisqa_mos_min": nisqa["mos_pred"].min(),
    "nisqa_mos_max": nisqa["mos_pred"].max(),
}])

summary

KeyError: 'mos_pred'

In [ ]:
import pandas as pd

df = pd.read_csv(NISQA_RESULT_PATH)

print(df.columns.tolist())
print(df.head())

NameError: name 'NISQA_RESULT_PATH' is not defined

In [ ]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

False
No GPU

In [ ]:
import os
import subprocess
from tqdm import tqdm

nisqa_scores = []

for path in tqdm(df["audio_path"]):

    try:

        cmd = [
            "python",
            "/content/NISQA/run_predict.py",
            "--mode",
            "predict_file",
            "--pretrained_model",
            "/content/NISQA/weights/nisqa.tar",
            "--deg",
            path
        ]

        result = subprocess.check_output(
            cmd,
            stderr=subprocess.STDOUT
        ).decode()

        score = None

        for line in result.split("\n"):

            if "MOS:" in line:

                score = float(
                    line.split("MOS:")[-1].strip()
                )

                break

        nisqa_scores.append(score)

    except Exception as e:

        print("FAILED:", path)

        nisqa_scores.append(None)

  2%|▏         | 17/1052 [02:08<2:10:37,  7.57s/it]

KeyboardInterrupt:

**MMS-TTS**

In [ ]:
!pip install -q torchmetrics[audio]
!pip install -q librosa soundfile pandas tqdm
!git clone https://github.com/gabrielmittag/NISQA.git

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 79.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 60.7 MB/s eta 0:00:00
  Building wheel for pesq (setup.py) ... done
Cloning into 'NISQA'...
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 258 (delta 55), reused 45 (delta 45), pack-reused 188 (from 1)
Receiving objects: 100% (258/258), 2.27 MiB | 6.34 MiB/s, done.
Resolving deltas: 100% (130/130), done.

In [ ]:
import os
import re
import torch
import pandas as pd
import librosa
from tqdm import tqdm
from torchmetrics.audio import NonIntrusiveSpeechQualityAssessment

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

nisqa = NonIntrusiveSpeechQualityAssessment(
    fs=16000
).to(device)

In [ ]:
df = pd.read_csv(
    "/content/drive/MyDrive/tts_benchmark/MMS_TTS_FAS/generation_metadata.csv"
)

df.head()

,audio_path,text,tts_runtime,audio_duration,tts_rtf
0,/content/drive/MyDrive/tts_benchmark/MMS_TTS_F...,جسد مزبور را در بیشهای که در گودی کوهستان قرار...,0.253061,5.680,0.044553
1,/content/drive/MyDrive/tts_benchmark/MMS_TTS_F...,لیدی گاگای تازه وارد به یکباره,0.429199,2.656,0.161596
2,/content/drive/MyDrive/tts_benchmark/MMS_TTS_F...,رازی را آشکار کردن,0.094803,2.048,0.046290
3,/content/drive/MyDrive/tts_benchmark/MMS_TTS_F...,ماه هاست سکوت کردم,0.088176,2.144,0.041127
4,/content/drive/MyDrive/tts_benchmark/MMS_TTS_F...,چه کسی این نامه را فرستاده است؟,0.096509,2.608,0.037005

In [ ]:
audio_files = df["audio_path"].tolist()

In [ ]:
rows = []

for file_path in tqdm(audio_files):

    waveform, sr = librosa.load(file_path, sr=16000)

    waveform = torch.tensor(waveform).unsqueeze(0).to(device)

    with torch.no_grad():
        mos_pred = nisqa(waveform)

    # FIX: handle multi-output tensor
    mos_pred = mos_pred.squeeze().detach().cpu().numpy()

    rows.append({
        "file": os.path.basename(file_path),

        "mos_pred": float(mos_pred[0]),
        "noi_pred": float(mos_pred[1]),
        "dis_pred": float(mos_pred[2]),
        "col_pred": float(mos_pred[3]),
        "loud_pred": float(mos_pred[4]),
    })

 55%|█████▌    | 583/1052 [05:32<04:23,  1.78it/s]

In [ ]:
nisqa_df = pd.DataFrame(rows)

nisqa_df.head()

In [ ]:
summary = pd.DataFrame([{
    "model": "MMS_TTS_FAS",
    "samples": len(nisqa_df),

    "nisqa_mos_mean": nisqa_df["mos_pred"].mean(),
    "nisqa_mos_std": nisqa_df["mos_pred"].std(),

    "noise_mean": nisqa_df["noi_pred"].mean(),
    "discontinuity_mean": nisqa_df["dis_pred"].mean(),
    "coloration_mean": nisqa_df["col_pred"].mean(),
    "loudness_mean": nisqa_df["loud_pred"].mean(),
}])

summary

###################################################### F5-TTS

In [ ]:
import os
import re
import torch
import pandas as pd
import librosa
from tqdm import tqdm
from torchmetrics.audio import NonIntrusiveSpeechQualityAssessment

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

nisqa = NonIntrusiveSpeechQualityAssessment(
    fs=16000
).to(device)

In [ ]:
METADATA_PATH = "/content/drive/MyDrive/tts_benchmark/f5tts_metadata.csv"
df = pd.read_csv(
    METADATA_PATH
)

df.head()

,idx,audio_path,text,tts_runtime,audio_duration,tts_rtf
0,0,/content/drive/MyDrive/tts_benchmark/f5tts_wav...,جسد مزبور را در بیشهای که در گودی کوهستان قرار...,4.837451,6.826667,0.708611
1,1,/content/drive/MyDrive/tts_benchmark/f5tts_wav...,لیدی گاگای تازه وارد به یکباره,2.082830,3.018667,0.689983
2,2,/content/drive/MyDrive/tts_benchmark/f5tts_wav...,رازی را آشکار کردن,1.426919,1.898667,0.751537
3,3,/content/drive/MyDrive/tts_benchmark/f5tts_wav...,ماه هاست سکوت کردم,1.457080,1.781333,0.817971
4,4,/content/drive/MyDrive/tts_benchmark/f5tts_wav...,چه کسی این نامه را فرستاده است؟,3.800935,4.608000,0.824856

In [ ]:
audio_files = df["audio_path"].tolist()

In [ ]:
import torch
import torch.nn.functional as F

MIN_LENGTH = 48000  # ~3 sec at 16kHz

results = []

for _, row in tqdm(df.iterrows(), total=len(df)):

    wav_path = row["audio_path"]

    waveform, sr = librosa.load(
        wav_path,
        sr=16000,
        mono=True
    )

    waveform = torch.tensor(
        waveform,
        dtype=torch.float32
    ).unsqueeze(0).to(device)

    # pad short files
    if waveform.shape[1] < MIN_LENGTH:

        pad_amount = MIN_LENGTH - waveform.shape[1]

        waveform = F.pad(
            waveform,
            (0, pad_amount),
            mode="constant",
            value=0
        )

    with torch.no_grad():
        scores = nisqa(waveform)

    scores = scores.squeeze().cpu().numpy()

    results.append({
        "audio_path": wav_path,
        "mos_pred": scores[0],
        "noi_pred": scores[1],
        "dis_pred": scores[2],
        "col_pred": scores[3],
        "loud_pred": scores[4],
    })

results_df = pd.DataFrame(results)

100%|██████████| 1052/1052 [01:55<00:00,  9.10it/s]

In [ ]:
results_df = pd.DataFrame(results)

print(results_df.head())
print("Samples:", len(results_df))

                                          audio_path  mos_pred  noi_pred  \
0  /content/drive/MyDrive/tts_benchmark/f5tts_wav...  4.603414  4.343653
1  /content/drive/MyDrive/tts_benchmark/f5tts_wav...  3.043146  3.692506
2  /content/drive/MyDrive/tts_benchmark/f5tts_wav...  1.409880  3.322807
3  /content/drive/MyDrive/tts_benchmark/f5tts_wav...  1.804087  3.235127
4  /content/drive/MyDrive/tts_benchmark/f5tts_wav...  2.712820  3.354430

   dis_pred  col_pred  loud_pred
0  4.647687  4.260246   4.467696
1  3.960283  2.996394   2.998669
2  2.103910  2.434198   1.476798
3  1.973861  2.006785   2.862428
4  3.627627  2.403161   2.858894
Samples: 1052

In [ ]:
summary = pd.DataFrame([{
    "model": "F5TTS",
    "samples": len(results_df),

    "nisqa_mos_mean": results_df["mos_pred"].mean(),
    "nisqa_mos_std": results_df["mos_pred"].std(),
    "nisqa_mos_min": results_df["mos_pred"].min(),
    "nisqa_mos_max": results_df["mos_pred"].max(),

    "noise_mean": results_df["noi_pred"].mean(),
    "noise_std": results_df["noi_pred"].std(),

    "discontinuity_mean": results_df["dis_pred"].mean(),
    "discontinuity_std": results_df["dis_pred"].std(),

    "coloration_mean": results_df["col_pred"].mean(),
    "coloration_std": results_df["col_pred"].std(),

    "loudness_mean": results_df["loud_pred"].mean(),
    "loudness_std": results_df["loud_pred"].std(),
}])

summary

,model,samples,nisqa_mos_mean,nisqa_mos_std,nisqa_mos_min,nisqa_mos_max,noise_mean,noise_std,discontinuity_mean,discontinuity_std,coloration_mean,coloration_std,loudness_mean,loudness_std
0,F5TTS,1052,3.217764,0.985317,0.65203,5.008183,3.706354,0.585276,3.670939,0.868614,3.286419,0.723163,3.511818,0.738657

In [ ]:
import os

SAVE_DIR = "/content/drive/MyDrive/tts_benchmark/F5TTS"
os.makedirs(SAVE_DIR, exist_ok=True)

In [ ]:
DETAIL_PATH = os.path.join(
    SAVE_DIR,
    "F5TTS_nisqa_scores.csv"
)

results_df.to_csv(
    DETAIL_PATH,
    index=False
)

print("Saved detailed scores:")
print(DETAIL_PATH)

Saved detailed scores:
/content/drive/MyDrive/tts_benchmark/F5TTS/F5TTS_nisqa_scores.csv

In [ ]:
SUMMARY_PATH = os.path.join(
    SAVE_DIR,
    "F5TTS_nisqa_summary.csv"
)

summary.to_csv(
    SUMMARY_PATH,
    index=False
)

print("Saved summary:")
print(SUMMARY_PATH)

Saved summary:
/content/drive/MyDrive/tts_benchmark/F5TTS/F5TTS_nisqa_summary.csv

**VITS_MMS**

In [ ]:
df = pd.read_csv(
    "/content/drive/MyDrive/tts_benchmark/VITS_MMS/metadata_fixed.csv"
)
df.head()

,audio_path,reference,prediction,sample_cer,prediction_fixed
0,/content/drive/MyDrive/tts_benchmark/VITS_MMS/...,جسد مزبور را در بیشهای که در گودی کوهستان قرار...,Hypothesis score ۴۶۰ ۸۷۹۵۴۷۱۱۹۱۴۰۶ y_sequence ...,6.983607,به صد مزبور را در بیشهای که در گودی کوهستان قر...
1,/content/drive/MyDrive/tts_benchmark/VITS_MMS/...,لیدی گاگای تازه وارد به یکباره,Hypothesis score ۱۴۸ ۳۴۱۶۵۹۵۴۵۸۹۸۴۴ y_sequence...,12.900000,دیدیگادای تازه وارد به یک بار
2,/content/drive/MyDrive/tts_benchmark/VITS_MMS/...,رازی را آشکار کردن,Hypothesis score ۶۶ ۱۹۴۸۷۷۶۲۴۵۱۱۷۲ y_sequence ...,20.333333,رازی را آشکار کردم
3,/content/drive/MyDrive/tts_benchmark/VITS_MMS/...,ماه هاست سکوت کردم,Hypothesis score ۸۹ ۳۱۲۷۶۷۰۲۸۸۰۸۶ y_sequence t...,20.444444,ماه هاست سکوت کردم
4,/content/drive/MyDrive/tts_benchmark/VITS_MMS/...,چه کسی این نامه را فرستاده است,Hypothesis score ۸۲ ۹۹۱۵۰۰۸۵۴۴۹۲۱۹ y_sequence ...,12.433333,چه کسی این نامه را فرستاده است

In [ ]:
audio_files = df["audio_path"].tolist()

In [ ]:
import torch
import torch.nn.functional as F

MIN_LENGTH = 48000  # ~3 sec at 16kHz

results = []

for _, row in tqdm(df.iterrows(), total=len(df)):

    wav_path = row["audio_path"]

    waveform, sr = librosa.load(
        wav_path,
        sr=16000,
        mono=True
    )

    waveform = torch.tensor(
        waveform,
        dtype=torch.float32
    ).unsqueeze(0).to(device)

    # pad short files
    if waveform.shape[1] < MIN_LENGTH:

        pad_amount = MIN_LENGTH - waveform.shape[1]

        waveform = F.pad(
            waveform,
            (0, pad_amount),
            mode="constant",
            value=0
        )

    with torch.no_grad():
        scores = nisqa(waveform)

    scores = scores.squeeze().cpu().numpy()

    results.append({
        "audio_path": wav_path,
        "mos_pred": scores[0],
        "noi_pred": scores[1],
        "dis_pred": scores[2],
        "col_pred": scores[3],
        "loud_pred": scores[4],
    })

results_df = pd.DataFrame(results)

  0%|          | 0/1052 [00:00<?, ?it/s]downloading https://github.com/gabrielmittag/NISQA/raw/refs/heads/master/weights/nisqa.tar to /root/.torchmetrics/NISQA/nisqa.tar
INFO:torchmetrics:downloading https://github.com/gabrielmittag/NISQA/raw/refs/heads/master/weights/nisqa.tar to /root/.torchmetrics/NISQA/nisqa.tar
100%|██████████| 1052/1052 [08:38<00:00,  2.03it/s]

In [ ]:
results_df = pd.DataFrame(results)

print(results_df.head())
print("Samples:", len(results_df))

                                          audio_path  mos_pred  noi_pred  \
0  /content/drive/MyDrive/tts_benchmark/VITS_MMS/...  4.132411  3.884502
1  /content/drive/MyDrive/tts_benchmark/VITS_MMS/...  3.973675  4.218812
2  /content/drive/MyDrive/tts_benchmark/VITS_MMS/...  3.673346  3.936614
3  /content/drive/MyDrive/tts_benchmark/VITS_MMS/...  4.535836  4.343703
4  /content/drive/MyDrive/tts_benchmark/VITS_MMS/...  4.700647  4.361373

   dis_pred  col_pred  loud_pred
0  4.190484  3.400829   3.831212
1  3.876844  3.952611   3.754727
2  4.209674  3.606870   3.639747
3  4.603020  4.420835   4.374726
4  4.638432  4.176515   4.413509
Samples: 1052

In [ ]:
summary = pd.DataFrame([{
    "model": "VITS MMS",
    "samples": len(results_df),

    "nisqa_mos_mean": results_df["mos_pred"].mean(),
    "nisqa_mos_std": results_df["mos_pred"].std(),
    "nisqa_mos_min": results_df["mos_pred"].min(),
    "nisqa_mos_max": results_df["mos_pred"].max(),

    "noise_mean": results_df["noi_pred"].mean(),
    "noise_std": results_df["noi_pred"].std(),

    "discontinuity_mean": results_df["dis_pred"].mean(),
    "discontinuity_std": results_df["dis_pred"].std(),

    "coloration_mean": results_df["col_pred"].mean(),
    "coloration_std": results_df["col_pred"].std(),

    "loudness_mean": results_df["loud_pred"].mean(),
    "loudness_std": results_df["loud_pred"].std(),
}])

summary

,model,samples,nisqa_mos_mean,nisqa_mos_std,nisqa_mos_min,nisqa_mos_max,noise_mean,noise_std,discontinuity_mean,discontinuity_std,coloration_mean,coloration_std,loudness_mean,loudness_std
0,VITS MMS,1052,3.91298,0.683041,0.999027,4.973138,4.010721,0.308024,3.98356,0.666573,3.584219,0.538124,3.841015,0.378278

In [ ]:
import os

SAVE_DIR = "/content/drive/MyDrive/tts_benchmark/VITS MMS"
os.makedirs(SAVE_DIR, exist_ok=True)

In [ ]:
DETAIL_PATH = os.path.join(
    SAVE_DIR,
    "VITS_MMS_nisqa_scores.csv"
)

results_df.to_csv(
    DETAIL_PATH,
    index=False
)

print("Saved detailed scores:")
print(DETAIL_PATH)

Saved detailed scores:
/content/drive/MyDrive/tts_benchmark/VITS MMS/VITS_MMS_nisqa_scores.csv

In [ ]:
SUMMARY_PATH = os.path.join(
    SAVE_DIR,
    "VITS_MMS_nisqa_summary.csv"
)

summary.to_csv(
    SUMMARY_PATH,
    index=False
)

print("Saved summary:")
print(SUMMARY_PATH)

Saved summary:
/content/drive/MyDrive/tts_benchmark/VITS MMS/VITS_MMS_nisqa_summary.csv